# coding: utf-8

"""
    Kingpick Admin API

    Provides APIs for tenant maintenance

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_cli_client
from cvtool_cli_client.rest import ApiException
from cvtool_cli_client.models.job import Job


class TestJob(unittest.TestCase):
    """ Job unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJob(self):
        """
        Test Job
        """
        model = cvtool_cli_client.models.job.Job()


if __name__ == '__main__':
    unittest.main()
