# coding: utf-8

"""
    Kingpick Admin API

    Provides APIs for tenant maintenance

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cvtool_cli_client
from cvtool_cli_client.rest import ApiException
from cvtool_cli_client.models.job_input_parameters import JobInputParameters


class TestJobInputParameters(unittest.TestCase):
    """ JobInputParameters unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobInputParameters(self):
        """
        Test JobInputParameters
        """
        model = cvtool_cli_client.models.job_input_parameters.JobInputParameters()


if __name__ == '__main__':
    unittest.main()
