# coding: utf-8

"""
    Kingpick Admin API

    Provides APIs for tenant maintenance

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .annotations import Annotations
from .error import Error
from .image_list_response import ImageListResponse
from .image_request import ImageRequest
from .image_response import ImageResponse
from .job import Job
from .job_input_parameters import JobInputParameters
from .job_step import JobStep
from .meta_list_response import MetaListResponse
from .new_job_request import NewJobRequest
from .project import Project
from .projects import Projects
from .settings import Settings
from .tenant import Tenant
from .tenants import Tenants
from .vision_annotations import VisionAnnotations
